prometheus:
  server:
    version: 1.3.1.linux-amd64
    install_dir: /opt
    source: 'https://github.com/prometheus/prometheus/releases/download/v1.3.1/prometheus-1.3.1.linux-amd64.tar.gz'
    source_hash: sha1=a5e476604086533951a81f5653ccc49141b057c5
    args:
      config_file: /etc/prometheus/prometheus.yml
      storage:
        local_path: /var/lib/prometheus/metrics
  alertmanager:
    version: 0.5.0.linux-amd64
    install_dir: /opt
    source: https://github.com/prometheus/alertmanager/releases/download/v0.5.0/alertmanager-0.5.0.linux-amd64.tar.gz
    source_hash: sha1=2669d6b0143896b634699e7d70f95f5da92ad94f
    args:
      config_file: /etc/alertmanager/alertmanager.yml
      storage:
        path: /var/lib/alertmanager
  exporters:
    node:
      version: 0.12.0.linux-amd64
      install_dir: /opt
      source: https://github.com/prometheus/node_exporter/releases/download/0.12.0/node_exporter-0.12.0.linux-amd64.tar.gz
      source_hash: md5=efe49b6fae4b1a5cb75b24a60a35e1fc
